git:
  overrideGpg: true
  # pagers:
  #   - colorArg: always
  #     pager: delta --dark --paging=never
gui:
  authorColors:
    "*": magenta
  showNumstatInFilesView: true
  skipRewordInEditorWarning: true
  tabWidth: 2
  theme:
    activeBorderColor:
      - "#D08770"
      - bold
    searchingActiveBorderColor:
      - "#D08770"
      - bold
    inactiveBorderColor:
      - "#4C566A"
      - bold
    selectedLineBgColor:
      - black
  border: single
  nerdFontsVersion: "3"
  spinner:
    frames:
      - "⠋"
      - "⠙"
      - "⠹"
      - "⠸"
      - "⠼"
      - "⠴"
      - "⠦"
      - "⠧"
      - "⠇"
      - "⠏"
    rate: 80
keybinding:
  files:
    viewResetOptions: <disabled>
